### ISSUE TITLE
Missing Imp Image

### ISSUE THREAD

**Issue by eukara** [dhewm/iddevnet#1]
I had scraped the site some time before it went offline.

http://icculus.org/~marco/notmine/id-dev/www.iddevnet.com/doom3/skins.html

You'll find the missing image for the imp there.

**Comment by DanielGibson** [comment]
Somehow I missed your backup - thanks a lot! :)

I already updated https://iddevnet.dhewm3.org/doom3/skins.html
(I didn't reintroduce that CSS mouseover hack, as it doesn't work well on mobile devices)
